#!/bin/bash
CNAME=`cat CNAME`
echo $CNAME
rsync --verbose -a -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet" --omit-dir-times --update --delete --delay-updates _site/ deploy@host.icoach.io:/var/www/html/anna-netreba
